sudo: required
services:
  - docker


before_install:
   - docker build -t jesufrancis31/docker-react -f Dockerfile.dev .

script:
  - docker run jesufrancis31/docker-react npm run test -- --coverage

