sudo: required
services:
  - docker


before_install:
   - docker build -t jesufrancis31/docker-react -f Dockerfile.dev .

script:
  - docker run jesufrancis31/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-west-2"
   app: "docker-react-EBS"
   env: "DockerReactEbs-env"
   bucket_name: "elasticbeanstalk-ap-south-1-334342053018"
   bucket_path: "docker-react-EBS"
   on:
    branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
        secure: "$AWS_SECRET_KEY"

   
